
server:
  port: 8765
  
spring:
  application:
    name: zuul   
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 30000
ribbon: 
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka: 
    enabled: true
zuul: 
  host: 
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
    
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
      
    cart-service:
      path: /cart-service/**
      serviceId: cart-service
        
    product-service:
      path: /product-service/**
      service-id: product-service
            
    order-service:
      path: /order-service/**
      service-id: order-service 
           