
spring:   
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

  application:
    name: user-service
    
# zipkin config    
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
      
      
# eureka config      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    
    
# Server config
server:
 port: 8200

management:
  endpoints:
    web:
      exposure:
        include: "*"
 