# In-memory databse 
spring:   
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

  application:
    name: cart-service
    
# zipkin config    
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
      
  sleuth:
    sampler:
      probability: 1.0
      
# eureka config      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka        
   
    
# Server config
server:
 port: 8400
 error:
  whitelabel:
    enabled: true 

management:
  endpoints:
    web:
      exposure:
        include: "*"
 